### PR TITLE
Alex tweaks

### PR DESCRIPTION
**Pull request by alex-r-bigelow**
I took some liberties with colors and sizing; namely:
- Switched the yellow color to fit with others in the theme (assuming ColorBrewer Categorical 8?)
- Got rid of all reds; instead use the highlight yellow for extra node links
- In diff mode, I grey the outlines of nodes that didn't change, instead of using red for the ones that did
- Flattened some of the extra UI colors to greys / blacks

Other changes:
- Hiding the key works
- Changed root node size
- Fixed a minor bug with mousing the root

*PLEASE* feel free to tell me if you don't like a change; I can totally revert stuff!

### CODE REVIEW

**Comment by alex-r-bigelow** [comment]
That makes sense. The main reason I tweaked the red outlines was that it clashed with the exclusive+run1 pink (I was actually thinking about using pink, until I realized you were already using it!)

Overall, it seems like this is the swatch you were using (this also happens to be my favorite)?
http://colorbrewer2.org/#type=qualitative&scheme=Dark2&n=8
With these diverging scales:
http://colorbrewer2.org/#type=diverging&scheme=PuOr&n=8
http://colorbrewer2.org/#type=diverging&scheme=PiYG&n=8

I'm tempted to swap that last scale for this one:
http://colorbrewer2.org/#type=diverging&scheme=BrBG&n=8
and use pink to highlight nodes that changed? Any thoughts?


As far as the wide title bar goes, I'm having trouble replicating it... is this in Safari, maybe?

**Comment by kawilliams** [comment]
I'm having the issue in Chrome. Not sure why? 

I'm on the fence about switching the pink-green for the teal-brown. I like the teal-brown better but I'm concerned about being able to see the border style. If it still looks fine (or if you want to tweak the default border color), then go for it.

**Comment by alex-r-bigelow** [comment]
This is what it looks like:

image

I *think* the header size should be fixed, but you might want to check it, because I couldn't figure out how to make it happen on my machine

**Comment by kawilliams** [comment]
The header works now, not sure why I was having issues.

**Pull request merged**
